### ISSUE TITLE
File conflict during installation

### ISSUE THREAD

**Issue by kewlfft** [LUCIT-Systems-and-Development/unicorn-binance-local-depth-cache#19]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug

#### Operating System? (include version)
- [x] Linux (include flavour) Arch Linux

#### Exact Python Version?
```
3.10.2
```
#### Pip Version?
```
21
```
#### Description of your issue
When I install the package it seems it has some duplicate files with `unicorn-binance-websocket-api`, because of the duplicates files it fails to install. Because `unicorn-binance-websocket-api`is a requirement for `unicorn-binance-local-depth-cache`you don't need to include duplicates of files already needed.

```
python-unicorn-binance-local-depth-cache: /usr/lib/python3.10/site-packages/tools/__init__.py exists in filesystem (owned by python-unicorn-binance-websocket-api)
python-unicorn-binance-local-depth-cache: /usr/lib/python3.10/site-packages/tools/__pycache__/__init__.cpython-310.opt-1.pyc exists in filesystem (owned by python-unicorn-binance-websocket-api)
python-unicorn-binance-local-depth-cache: /usr/lib/python3.10/site-packages/tools/__pycache__/__init__.cpython-310.pyc exists in filesystem (owned by python-unicorn-binance-websocket-api)
python-unicorn-binance-local-depth-cache: /usr/lib/python3.10/site-packages/tools/__pycache__/get_used_module_version.cpython-310.opt-1.pyc exists in filesystem (owned by python-unicorn-binance-websocket-api)
python-unicorn-binance-local-depth-cache: /usr/lib/python3.10/site-packages/tools/__pycache__/get_used_module_version.cpython-310.pyc exists in filesystem (owned by python-unicorn-binance-websocket-api)
python-unicorn-binance-local-depth-cache: /usr/lib/python3.10/site-packages/tools/get_used_module_version.py exists in filesystem (owned by python-unicorn-binance-websocket-api)
Errors occurred, no packages were upgraded.

```

**Comment by oliver-zehentleitner** [comment]
how are you doing the installation?

**Comment by kewlfft** [comment]
I have created the package for Arch Linux and install with pacman, this is the standard installation for Arch Linux and it detects a file conflict. I can install overwriting the conflict, however I think there is an unexpected file conflict in the original distribution, otherwise this should not happen. _init_ and _get_used_module_version_ is already installed with `unicorn-binance-websocket-api`.

**Comment by oliver-zehentleitner** [comment]
ok, i think i understand the reason.

the package you build this lib contains files like:
exceptions.py 
 __init__.py  
manager.py  
__pycache__

but i guess it must look like:
unicorn_binance_local_depth_cache/exceptions.py 
unicorn_binance_local_depth_cache/__init__.py  
unicorn_binance_local_depth_cache/manager.py  
unicorn_binance_local_depth_cache/__pycache__

**Comment by oliver-zehentleitner** [comment]
why do you not use pip?

**Comment by kewlfft** [comment]
Arch Linux uses pacman instead of pip. It is the 2 files in _/tools_: `__init__` and `get_used_module_version` only that are clashing. They are in _/tools_ for both libraries. I agree with you for the other files, they are in unicorn_binance_local_depth_cache/ and are not clashing.

**Comment by oliver-zehentleitner** [comment]
no. arch uses pacman instead of yum, apt, emerge, etc, but pip is an python internal package manager like nodes npm wich exists on every linux and unix plattform, even on windows :)

Just install pip and use it, will make life more easy :)
https://www.archlinux.de/packages/extra/x86_64/python-pip

**Comment by oliver-zehentleitner** [comment]
actually packages should be isolated from each other, the package you build must have a mistake ....

**Comment by kewlfft** [comment]
I am an Arch Linux maintainer and we package all the python libs, we don't rely on pip. In both source packages the _tools_ directory is at the same level, it installs in `/usr/lib/python3.10/site-packages/tools` and one package being a requirement for the other one it will necessarily clash.
I don't know if you could name differently or move it as a sub-directory of ubldc. I suppose pip does the same pacman does but just overwrites silently the file. 
Here is the ArchLinux package which will give you access to the Arch Linux + derivatives (Manjaro...) communities: https://aur.archlinux.org/packages/python-unicorn-binance-local-depth-cache

**Comment by oliver-zehentleitner** [comment]
i think the folder `tools` should be the package name 
`/lib/python3.9/site-packages/unicorn_binance_local_depth_cache/manager.py`

thats how it looks like in debian after installation with pip and its working then

**Comment by kewlfft** [comment]
yes this file is fine, it installs in the package name directory. I am referring to `/tools/get_used_module_version.py` and `/tools/__init__.py` these are the only 2 files that are causing conflict.

**Comment by oliver-zehentleitner** [comment]
__init__.py is usualy an empty file and can get replaced.

i dont know what is get_used_module_version.py

**Comment by oliver-zehentleitner** [comment]
i cant really help you with this issue. maybe you can find some hints in the arch community.

if you have specific questions i can help you if i know it.

please close this issue as soon as you found your answers! thanks

**Comment by kewlfft** [comment]
Tools/get_used_module_version.py is a file in your repo and it is the one causing an issue. If you don't need it you can delete this tools directory from the source and the problem is solved.

**Comment by oliver-zehentleitner** [comment]
ah, its that :D 

actually i want to create one file like that and collect all versions of all unicorn binance suite packages and store this file in the unicorn binance suite repo. (a task of the next two weeks)

but this files are not important for the package. are you not able to filter them out?

**Comment by kewlfft** [comment]
yes I can delete these files from the installation for the moment, if you can find a solution upstream to avoid the duplicates that would be great as well. This can be closed.

**Comment by oliver-zehentleitner** [comment]
the file get_used_module_version.py  will soon be removed from all repos except unicorn-binance-suite. (websocket and depthcache is ready now, unifornfy and rest is missing)

but there will be other new files with same name. but they are never important to run the libs.

i think it can not be up to the lib authors to not use same filenames with other libs. if this is a problem, the packaging is doing something wrong...

I close this.

**Comment by kewlfft** [comment]
Thanks for these explanations. 
You can of course have files with the same name / same location and different contents in your libs. Then these files will overwrite each other when more than 1 of your libs is installed: this triggers the warning by pacman, pip may overwrite silently the file. I am now removing these files in the packaging.
From my experience with dozens of python libs, this is quite uncommon that libs that can be installed together contain the same file name at the same location with a different content.

**Comment by oliver-zehentleitner** [comment]
We now provide source files and wheels on pypi: https://pypi.org/project/unicorn-binance-websocket-api/#files

the source files are cleaned and should not contain anything else then the lib.

Maybe you can use that in the arch packaging... best regards.

**Comment by kewlfft** [comment]
yes this is much cleaner, I've  updated the package, are all your binance libs in pypi now? I will update the 3 other packages in this case.

**Comment by oliver-zehentleitner** [comment]
all latest versions are clean, sdist and wheel!
