### ISSUE TITLE
Query order book data in the form of candlesticks?

### ISSUE THREAD

**Issue by minhajk21** [LUCIT-Systems-and-Development/unicorn-binance-local-depth-cache#29]
### Is your feature request related to a problem? Please describe.

NA

### Describe the solution you'd like.

Functionality to aggregate tick data into the form of candlesticks such that it matches the format and frequency of Kline data from other binance web socket data.

**Comment by oliver-zehentleitner** [comment]
Such a feature does not fit this module! If you would like to have something like this developed individually by me, you are welcome to contact me here: https://www.lucit.tech/get-support.html

I am closing this issue.
