### ISSUE TITLE
Uncontrolling growth of elements in lists of asks and bids in Depth Cache Manager

### ISSUE THREAD

**Issue by chubatrik** [LUCIT-Systems-and-Development/unicorn-binance-local-depth-cache#45]
### Discussed in https://github.com/LUCIT-Systems-and-Development/unicorn-binance-local-depth-cache/discussions/44

<div type='discussions-op-text'>

<sup>Originally posted by **chubatrik** October 29, 2024</sup>
### Description
When I create a DC and taking out bids and asks, an amount of elements in theese lists are growing without any border. The amount always starts about 1000 and growing up. 

### Results:
When I start the program: 
![Screenshot_1](https://github.com/user-attachments/assets/a055bef3-3a89-48f6-b80e-9aa21c3a3c54)
After 15 minutes of working:
![image](https://github.com/user-attachments/assets/04ef0133-c408-4a31-9a18-4c1acae3d0d7)

### Source code:
```coin = "ethusdt"
ubldc = BinanceLocalDepthCacheManager(exchange="binance.com-futures", depth_cache_update_interval=100)
ubldc.create_depthcache(coin)

while True:
    try:
        try:
            asks = ubldc.get_asks(coin)
            bids = ubldc.get_bids(coin)
        except DepthCacheOutOfSync:
            asks = "Out of sync!"
            bids = "Out of sync!"
        print(f"Bids: {len(bids)}, asks: {len(asks)}")
        time.sleep(1)
    except (Exception, KeyboardInterrupt) as k:
        print(k)
        ubldc.stop_manager()
        print(f"finished")
        exit()</div>

**Comment by oliver-zehentleitner** [comment]
Thanks for the tip!

I think you have noticed an incompleteness in the allgorythm:
![grafik](https://github.com/user-attachments/assets/064db315-5769-45ed-84c2-9cb36c245a5b)
![grafik](https://github.com/user-attachments/assets/1206ee26-e451-404a-a80b-3eb1df4b793d)

I will implement this and publish an update.

**Comment by chubatrik** [comment]
Good! But it would be great to make amount of elements a choice. Let's say maximum will be 5000 elements, but we can choose from 100 to 5000 when creating a depth or a manager, something like that.

**Comment by oliver-zehentleitner** [comment]
I wouldn't do that. Since everything above the 1000 element is no longer kept up to date by diff updates, I consider these entries to be orphaned and no longer trustworthy. They will continue to sit around between the valid entries. 

It could even happen that there are more orphaned entries in the last 1000 than valid ones.

It would be more orderly to apply updates and remove everything that has slipped out of the scope.

**Comment by oliver-zehentleitner** [comment]
The test file: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-local-depth-cache/blob/master/dev/issue/45.py

**Comment by oliver-zehentleitner** [comment]
Please update UBWA to 2.8.1 and UBLDC to 2.7.0, all fixes are included!

Best regards!

**Comment by oliver-zehentleitner** [comment]
An article to this issue: https://blog.technopathy.club/your-binance-order-book-is-wrong-here-s-why
