### ISSUE TITLE
stop_depth_cache returns "error_msg: `stream_id` is missing!"

### ISSUE THREAD

**Issue by chubatrik** [LUCIT-Systems-and-Development/unicorn-binance-local-depth-cache#46]
### Solution to Issue cannot be found in the documentation or other Issues and also occurs in the latest version of this library.

- [X] I checked the documentation and other Issues. I am using the latest version of this library.

### Version of this library.

lucit_licensing_python: 1.8.2
unicorn_fy: 0.14.2
unicorn_binance_local_depth_cache: 2.6.0
unicorn_binance_rest_api: 2.6.1
unicorn_binance_trailing_stop_loss: not found
unicorn_binance_websocket_api: 2.8.0

### Hardware?

Local server/workstation

### Operating System?

Windows

### Python version?

Python3.12

### Used endpoint?

concerns all

### Issue

When I try to stop_depth_cache, it returns: _"BinanceWebSocketApiManager.unsubscribe_from_stream() - error_msg: stream_id is missing!"_
### Screenshot:
![image](https://github.com/user-attachments/assets/8b5854da-6dc5-43c5-8c5e-649bb724eff2)
### Source code:
```
ubldc = BinanceLocalDepthCacheManager(exchange="binance.com-futures", depth_cache_update_interval=100)
coins = ['ethusdt', 'DYDXUSDT', "ALGOUSDT", "btcusdt"]
ubldc.create_depthcache(coins)
ubldc.stop_depthcache("btcusdt")
ubldc.stop_manager()
print(f"finished")
exit()

**Comment by oliver-zehentleitner** [comment]
Thanks I fixed it!

Test file: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-local-depth-cache/blob/master/dev/issue/46.py

**Comment by oliver-zehentleitner** [comment]
Please update UBWA to 2.8.1 and UBLDC to 2.7.0, all fixes are included!

Best regards!
